#include <stdio.h>
// Problem : Show the output to be generated by the print() function [20-21]
int main()
{
    int a = 0x7c5;
    float x = 13.25;
    printf("%-07X %#7g %10.2e", a, x, x);
    return 0;
}